#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr  8 16:50:39 2018

@author: joshwork
"""

from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()

"""
>>> clf = tree.DecisionTreeClassifier()
>>> clf = clf.fit(iris.data, iris.target)
"""